name: json_preview
description: A lightweight and customizable Flutter widget for displaying JSON data in a collapsible tree view.
version: 0.1.3
homepage: https://github.com/thejas-dev/json_preview

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: 
  uses-material-design: true
